-changed some gridhttps profile variables default value -added different behavior depending if the installation is sl5 or sl6 -made the path of tomcat files parameterized on tomcat version

diff --git a/functions/config_storm_secure_tomcat b/functions/config_storm_secure_tomcat
--- a/functions/config_storm_secure_tomcat
+++ b/functions/config_storm_secure_tomcat
@@ -31,16 +31,22 @@
 ##############################################################################
 
 config_storm_secure_tomcat_check () {
-
- requires $1 TOMCAT_USER STORM_GRIDHTTPS_SERVER_PORT STORM_GRIDHTTPS_HTTPS_SERVER_PORT TOMCAT_HOSTCERT_LOCATION TOMCAT_HOSTKEY_LOCATION TRUSTMANAGER_CRL_UPDATE_INTERVAL X509_CERT_DIR X509_HOST_CERT X509_HOST_KEY
- return $?
-
+  ret=0
+  requires $1 TOMCAT_USER STORM_GRIDHTTPS_SERVER_PORT STORM_GRIDHTTPS_HTTPS_SERVER_PORT TOMCAT_HOSTCERT_LOCATION TOMCAT_HOSTKEY_LOCATION TRUSTMANAGER_CRL_UPDATE_INTERVAL X509_CERT_DIR X509_HOST_CERT X509_HOST_KEY
+  let "ret |= $?"
+  detect_tomcat
+  if [ -z ${TOMCAT_VERSION} ]; then
+    yaimlog ERROR "Tomcat is probably not installed !"
+    yaimlog ERROR "${YERRORSTR}"
+    
+  fi
+  return $ret
 }
 
 config_storm_secure_tomcat_setenv () {
 
-  if [ -f /etc/tomcat5/tomcat5.conf ]; then
-    source /etc/tomcat5/tomcat5.conf
+  if [ -f /etc/${TOMCAT_VERSION}/${TOMCAT_VERSION}.conf ]; then
+    source /etc/${TOMCAT_VERSION}/${TOMCAT_VERSION}.conf
     yaimgridenv_set CATALINA_HOME ${CATALINA_HOME}
   fi
 }
@@ -58,28 +64,17 @@ if [ ! -f /etc/java/java.conf ]; then
   exit ${YEX_NOSUCHFILE}
 fi
 
-yaimlog INFO "Check that tomcat is installed"
-if [ ! -f /etc/tomcat5/tomcat5.conf ]; then
-    yestr ${YEX_NOSUCHFILE}
-    yaimlog ERROR "/etc/tomcat5/tomcat5.conf doesn't exist. Tomcat is probably not installed !"
-    yaimlog ERROR "${YERRORSTR}"
-    exit ${YEX_NOSUCHFILE}
-fi
-
 yaimlog INFO "Stop tomcat in case it's running"
-service tomcat5 stop 
+service ${TOMCAT_VERSION} stop 
 
 ####@ Find Tomcat's webapps dir
 if [ ! -d "${CATALINA_BASE}/conf" ]; then
     CATALINA_BASE=${CATALINA_HOME}
-fi
-if [ ! -d "${CATALINA_BASE}/conf" ]; then
-    CATALINA_BASE="/var/tomcat5"
-fi
-if [ ! -d "${CATALINA_BASE}/conf" ]; then
-    CATALINA_BASE="/var/lib/tomcat5"
-fi
-if [ ! -d "${CATALINA_BASE}/conf" ]; then
+elif [ ! -d "${CATALINA_BASE}/conf" ]; then
+    CATALINA_BASE="/var/${TOMCAT_VERSION}"
+elif [ ! -d "${CATALINA_BASE}/conf" ]; then
+    CATALINA_BASE="/var/lib/${TOMCAT_VERSION}"
+elif [ ! -d "${CATALINA_BASE}/conf" ]; then
     yaimlog ABORT "ERROR: Could not find CATALINA_BASE"
     exit 1
 fi
@@ -116,17 +111,23 @@ chmod 400 ${TOMCAT_HOSTKEY_LOCATION}
 ####@ Configure the tomcat server itself
 
 ####@ Replace server.xml with the one defining the secure connector
-yaimlog INFO "Configuring /etc/tomcat5/server.xml..."
-if [ ! -f /etc/tomcat5/server.xml.storm.saved ] ; then
-	cp -f /etc/tomcat5/server.xml /etc/tomcat5/server.xml.storm.saved
+yaimlog INFO "Configuring /etc/${TOMCAT_VERSION}/server.xml..."
+if [ ! -f /etc/${TOMCAT_VERSION}/server.xml.storm.saved ] ; then
+	cp -f /etc/${TOMCAT_VERSION}/server.xml /etc/${TOMCAT_VERSION}/server.xml.storm.saved
 fi
 
-cat > /etc/tomcat5/server.xml << EOT
+if [ "${TOMCAT_VERSION}" == "tomcat5" ]; then
+	LISTENERS='<Listener className="org.apache.catalina.storeconfig.StoreConfigLifecycleListener"/>'
+elif [ "${TOMCAT_VERSION}" == "tomcat6" ]; then
+	LISTENERS=$(echo '<Listener className="org.apache.catalina.core.JasperListener" /><Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />' | sed 's/>/>\n/g')
+fi
+
+cat > /etc/${TOMCAT_VERSION}/server.xml << EOT
 <Server port="8005" shutdown="SHUTDOWN">
   <Listener className="org.apache.catalina.core.AprLifecycleListener" />
   <Listener className="org.apache.catalina.mbeans.ServerLifecycleListener" />
   <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
-  <Listener className="org.apache.catalina.storeconfig.StoreConfigLifecycleListener"/>
+  $LISTENERS
   <GlobalNamingResources>
     <Environment name="simpleValue" type="java.lang.Integer" value="30"/>
     <Resource name="UserDatabase" auth="Container"
@@ -157,7 +158,7 @@ cat > /etc/tomcat5/server.xml << EOT
      secure="true"
      clientAuth="true"
      sslProtocol="TLS"
-     log4jConfFile="/etc/tomcat5/log4j-trustmanager.properties"
+     log4jConfFile="/etc/${TOMCAT_VERSION}/log4j-trustmanager.properties"
      sslCAFiles="/etc/grid-security/certificates/*.0"
      crlFiles="/etc/grid-security/certificates/*.r0"
      sslKey="${TOMCAT_HOSTKEY_LOCATION}"
@@ -174,22 +175,31 @@ cat > /etc/tomcat5/server.xml << EOT
 </Server>
 EOT
 
-chown $TOMCAT_USER:$TOMCAT_USER /etc/tomcat5/server.xml
+chown $TOMCAT_USER:$TOMCAT_USER /etc/${TOMCAT_VERSION}/server.xml
 
 ####@ Copy log4j-trustmanager.properties into place
-ln -sf /var/lib/trustmanager-tomcat/log4j-trustmanager.properties /usr/share/tomcat5/conf/
-chown $TOMCAT_USER:$TOMCAT_USER /usr/share/tomcat5/conf/log4j-trustmanager.properties
+ln -sf /var/lib/trustmanager-tomcat/log4j-trustmanager.properties /usr/share/${TOMCAT_VERSION}/conf/
+chown $TOMCAT_USER:$TOMCAT_USER /usr/share/${TOMCAT_VERSION}/conf/log4j-trustmanager.properties
 
 yaimlog INFO "Copying trustmanager deps to tomcat server lib directory.." 
 # log4j
-build-jar-repository /var/lib/tomcat5/common/lib log4j
+if [ "${TOMCAT_VERSION}" == "tomcat5" ]; then
+	build-jar-repository /var/lib/tomcat5/common/lib log4j
+elif [ "${TOMCAT_VERSION}" == "tomcat6" ]; then
+	build-jar-repository /usr/share/tomcat6/lib log4j
+fi
+
 # bouncy castle has changed packaging between 1.37 and 1.41:
 if [ -f /usr/share/java-ext/bouncycastle-jdk1.5/bcprov.jar ]; then
   # location <= 1.37
-  ln -fs /usr/share/java-ext/bouncycastle-jdk1.5/bcprov.jar /var/lib/tomcat5/common/lib/bcprov.jar
+  ln -fs /usr/share/java-ext/bouncycastle-jdk1.5/bcprov.jar /var/lib/${TOMCAT_VERSION}/common/lib/bcprov.jar
 elif [ -f /usr/share/java/bcprov.jar ]; then
   # location >= 1.41
-  build-jar-repository /var/lib/tomcat5/common/lib bcprov
+  if [ "${TOMCAT_VERSION}" == "tomcat5" ]; then
+	build-jar-repository /var/lib/tomcat5/common/lib lbcprov
+  elif [ "${TOMCAT_VERSION}" == "tomcat6" ]; then
+	build-jar-repository /usr/share/tomcat6/lib bcprov
+  fi
 else
   # something unknown has happened
   yestr ${YEX_NOSUCHFILE}
@@ -198,9 +208,16 @@ else
   exit ${YEX_NOSUCHFILE}
 fi
 
-ln -fs /usr/share/java/trustmanager.jar /var/lib/tomcat5/common/lib/
-ln -fs /usr/share/java/trustmanager-tomcat.jar /var/lib/tomcat5/server/lib/
-ln -fs /usr/share/java/vomsjapi.jar /var/lib/tomcat5/common/lib/
+if [ "${TOMCAT_VERSION}" == "tomcat5" ]; then
+	ln -fs /usr/share/java/trustmanager.jar /var/lib/tomcat5/common/lib/
+	ln -fs /usr/share/java/trustmanager-tomcat.jar /var/lib/tomcat5/server/lib/
+	ln -fs /usr/share/java/vomsjapi.jar /var/lib/tomcat5/common/lib/
+  elif [ "${TOMCAT_VERSION}" == "tomcat6" ]; then
+	ln -fs /usr/share/java/trustmanager.jar /usr/share/tomcat6/lib
+	ln -fs /usr/share/java/trustmanager-tomcat.jar /usr/share/tomcat6/lib
+	ln -fs /usr/share/java/vomsjapi.jar /usr/share/tomcat6/lib
+  fi
+
 
 ####@ Defining JAVA_HOME in the Tomcat configuration file
 yaimlog INFO "Defining JAVA_HOME in the Tomcat configuration file"
@@ -249,12 +266,12 @@ else
 fi
 
 # Add JAVA_HOME if not already defined with the right value
-if [ ! `grep -q ^JAVA_HOME=${JAVA_HOME} /etc/tomcat5/tomcat5.conf` ]; then
-  cp /etc/tomcat5/tomcat5.conf /etc/tomcat5/tomcat5.conf.old    
+if [ ! `grep -q ^JAVA_HOME=${JAVA_HOME} /etc/${TOMCAT_VERSION}/${TOMCAT_VERSION}.conf` ]; then
+  cp /etc/${TOMCAT_VERSION}/${TOMCAT_VERSION}.conf /etc/${TOMCAT_VERSION}/${TOMCAT_VERSION}.conf.old    
   # Comment existing definitions
-  sed -i 's/^JAVA_HOME/# The following line was commented out by yaim\n# JAVA_HOME/g' /etc/tomcat5/tomcat5.conf 
-  echo "# JAVA_HOME defined by yaim in `date`" >> /etc/tomcat5/tomcat5.conf
-  echo "JAVA_HOME=${JAVA_HOME}" >> /etc/tomcat5/tomcat5.conf
+  sed -i 's/^JAVA_HOME/# The following line was commented out by yaim\n# JAVA_HOME/g' /etc/${TOMCAT_VERSION}/${TOMCAT_VERSION}.conf 
+  echo "# JAVA_HOME defined by yaim in `date`" >> /etc/${TOMCAT_VERSION}/${TOMCAT_VERSION}.conf
+  echo "JAVA_HOME=${JAVA_HOME}" >> /etc/${TOMCAT_VERSION}/${TOMCAT_VERSION}.conf
 fi
 
 return 0
diff --git a/functions/config_storm_tomcat_default_servlet b/functions/config_storm_tomcat_default_servlet
--- a/functions/config_storm_tomcat_default_servlet
+++ b/functions/config_storm_tomcat_default_servlet
@@ -30,10 +30,17 @@
 ##############################################################################
 
 function config_storm_tomcat_default_servlet_check () {
-
+  
+  ret=0
   requires $1 STORM_BACKEND_HOST STORM_BACKEND_REST_SERVICES_PORT TOMCAT_CONTEXT_DEPLOY_FOLDER
-  return $?
-
+  let "ret |= $?"
+  detect_tomcat
+  if [ -z ${TOMCAT_VERSION} ]; then
+    yaimlog ERROR "Tomcat is probably not installed !"
+    yaimlog ERROR "${YERRORSTR}"
+    
+  fi
+  return $ret
 }
 
 function config_storm_tomcat_default_servlet_setenv () {
@@ -80,6 +87,20 @@ function config_storm_tomcat_default_servlet () {
   #set_template_value server.port ${STORM_BACKEND_REST_SERVICES_PORT} ${FILE}
   sed --in-place "s/@server.port@/$STORM_BACKEND_REST_SERVICES_PORT/g" ${FILE}
   #set_template_value contextDeployFolder ${TOMCAT_CONTEXT_DEPLOY_FOLDER} ${FILE}
+  
+  ########################################################################
+  # Fix of a bug in sl6 compliance. 
+  # The default value of variable TOMCAT_CONTEXT_DEPLOY_FOLDER loaded from  
+  # se_storm_gridhttps.pre default file for se_storm_gridhttps profile
+  # is specific for tomcat5. On SL6 if its value has not been modified by the user 
+  # have to be changed to tomcat6 corresponding path 
+  ######################################################
+  if [ "${TOMCAT_VERSION}" == "tomcat6" ]; then
+  	if [ "$TOMCAT_CONTEXT_DEPLOY_FOLDER" == "/usr/share/tomcat5/conf/Catalina/localhost" ]; then
+  		TOMCAT_CONTEXT_DEPLOY_FOLDER="/usr/share/tomcat6/conf/Catalina/localhost"
+  		yaimgridenv_set TOMCAT_CONTEXT_DEPLOY_FOLDER ${TOMCAT_CONTEXT_DEPLOY_FOLDER} 
+  	fi
+  fi
   sed --in-place "s/@contextDeployFolder@/`echo $TOMCAT_CONTEXT_DEPLOY_FOLDER | sed 's/\//\\\\\//g'`/g" ${FILE}
   #==========================================================
 
@@ -90,7 +111,7 @@ function config_storm_tomcat_default_servlet () {
 
   # Save the original web.xml
    
-  ORIGINAL_FILE="/usr/share/tomcat5/conf/${FILE_NAME}"     # Configuration filename
+  ORIGINAL_FILE="/usr/share/${TOMCAT_VERSION}/conf/${FILE_NAME}"     # Configuration filename
   ORIGINAL_FILE_B="${ORIGINAL_FILE}.storm.saved"      # Backup configuration filename (if needed)
   
   if [ ! -L ${ORIGINAL_FILE} -a -f ${ORIGINAL_FILE} ]; then
