-updated se_storm_gridhttps profile to StoRM GridHTTPs 2.0 -removed useless function config-storm-sslkey

diff --git a/functions/config_storm_gridhttps_dir b/functions/config_storm_gridhttps_dir
--- a/functions/config_storm_gridhttps_dir
+++ b/functions/config_storm_gridhttps_dir
@@ -32,7 +32,7 @@
 
 function config_storm_gridhttps_dir_check () {
 
-  requires $1 STORM_GRIDHTTPS_ENABLED STORM_DEFAULT_ROOT STORM_STORAGEAREA_LIST TOMCAT_USER
+  requires $1 STORM_DEFAULT_ROOT STORM_STORAGEAREA_LIST TOMCAT_USER
   return $?
 
 }
@@ -47,34 +47,29 @@ function config_storm_gridhttps_dir () {
 
   FUNCTION="config_storm_gridhttps_dir"
 
-  # Convert in lowercase
-  STORM_GRIDHTTPS_ENABLED=`echo ${STORM_GRIDHTTPS_ENABLED} | tr '[:upper:]' '[:lower:]'`
-  # Convert spaces to commas
 
-  if [ "x${STORM_GRIDHTTPS_ENABLED}" == "xtrue" ]; then
-	# Set Read Extended ACL for the service for the Storage Area directories
-	  for SA in $STORM_STORAGEAREA_LIST; do
-	    # Convert case
-	    SA_UPP=`echo ${SA} | tr '[:lower:]' '[:upper:]'`
-	    SA_LOW=`echo ${SA} | tr '[:upper:]' '[:lower:]'`
-	
-	    # Remove DNS-like characters from SA_UPP names
-	    SA_UPP=`echo ${SA_UPP} | sed -e 's/-//g' -e 's/\.//g'`
-	
-	    x=STORM_${SA_UPP}_ROOT
-	    dir=${!x:-${STORM_DEFAULT_ROOT}/${SA_LOW}}
-	
-	    if [ -d ${dir} ]; then
-	      yaimlog DEBUG "${FUNCTION}: Setting Read Extended ACL to '${TOMCAT_USER}' group for ${dir}"; 
-	      setfacl -m g:${STORM_USER}:rx ${dir};
-	    else
-	      yaimlog ERROR "${FUNC}: Unable to use ${dir} as Storage Area root!"
-	      yestr ${YEX_NOSUCHFILE}
-	      yaimlog ERROR "${YERRORSTR}"
-	      exit ${YEX_NOSUCHFILE}
-	    fi
-	  done
-  fi
+  # Set Read Extended ACL for the service for the Storage Area directories
+  for SA in $STORM_STORAGEAREA_LIST; do
+    # Convert case
+    SA_UPP=`echo ${SA} | tr '[:lower:]' '[:upper:]'`
+    SA_LOW=`echo ${SA} | tr '[:upper:]' '[:lower:]'`
+
+    # Remove DNS-like characters from SA_UPP names
+    SA_UPP=`echo ${SA_UPP} | sed -e 's/-//g' -e 's/\.//g'`
+
+    x=STORM_${SA_UPP}_ROOT
+    dir=${!x:-${STORM_DEFAULT_ROOT}/${SA_LOW}}
+
+    if [ -d ${dir} ]; then
+      yaimlog DEBUG "${FUNCTION}: Setting Read Extended ACL to '${TOMCAT_USER}' group for ${dir}"; 
+      setfacl -m g:${STORM_USER}:rx ${dir};
+    else
+      yaimlog ERROR "${FUNC}: Unable to use ${dir} as Storage Area root!"
+      yestr ${YEX_NOSUCHFILE}
+      yaimlog ERROR "${YERRORSTR}"
+      exit ${YEX_NOSUCHFILE}
+    fi
+  done
   
   # Exit with success
   return 0
diff --git a/functions/config_storm_start_gridhttps b/functions/config_storm_start_gridhttps
--- a/functions/config_storm_start_gridhttps
+++ b/functions/config_storm_start_gridhttps
@@ -17,54 +17,53 @@
 # limitations under the License.
 ##############################################################################
 #
-# NAME :        config_storm_secure_tomcat
+# NAME :        config_storm_start_gridhttps
 #
-# DESCRIPTION : This function configures tomcat
+# DESCRIPTION : This function starts StoRM GridHTTPs
 #
 # AUTHORS :     michele.dibenedetto@cnaf.infn.it
 #
-# NOTES :       This function is taken from the config_secure_tomcat function written
-#               by Akos Frohner (Akos.Frohner@cern.ch) and Maria Alandes Pradillo (Maria.Alandes.Pradillo@cern.ch).
+# NOTES :       
 #
 # YAIM MODULE:  yaim-storm
 #                 
 ##############################################################################
 
-config_storm_start_tomcat_check () {
+config_storm_start_gridhttps_check () {
 
-  ret=0
-  detect_tomcat
-  if [ -z ${TOMCAT_VERSION} ]; then
-    yaimlog ERROR "Tomcat is probably not installed !"
-    yaimlog ERROR "${YERRORSTR}"
-    let "ret |= 1"
-  fi
-  return $ret
 
 }
 
-config_storm_start_tomcat_setenv () {
+config_storm_start_gridhttps_setenv () {
 
   yaimlog INFO "No enviroment variables to set."
 }
 
-config_storm_start_tomcat () {
+config_storm_start_gridhttps () {
 
 
-####@ Check whether tomcat and java are installed
-
-yaimlog INFO "Check that java is installed"
-if [ ! -f /etc/java/java.conf ]; then
-  yestr ${YEX_NOSUCHFILE}
-  yaimlog ERROR "/etc/java/java.conf doesn't exist. Java is probably not installed !"
-  yaimlog ERROR "${YERRORSTR}"
-  exit ${YEX_NOSUCHFILE}
-fi
-
-####@ Restart Tomcat
-yaimlog INFO "Starting Tomcat"
-service ${TOMCAT_VERSION} start
-
-return 0
+	####@ Check whether GridHTTPs and java are installed
+	
+	yaimlog INFO "Check that java is installed"
+	if [ ! -f /etc/java/java.conf ]; then
+	  yestr ${YEX_NOSUCHFILE}
+	  yaimlog ERROR "/etc/java/java.conf doesn't exist. Java is probably not installed !"
+	  yaimlog ERROR "${YERRORSTR}"
+	  exit ${YEX_NOSUCHFILE}
+	fi
+	
+	yaimlog INFO "Check that GridHTTPs is installed"
+	if [ ! -d /etc/storm/gridhttps-server ]; then
+	  yestr ${YEX_NOSUCHFILE}
+	  yaimlog ERROR "/etc/storm/gridhttps-server doesn't exist. StoRM GridHTTPs is probably not installed !"
+	  yaimlog ERROR "${YERRORSTR}"
+	  exit ${YEX_NOSUCHFILE}
+	fi
+	
+	yaimlog INFO "Starting GridHTTPs"
+	service storm-gridhttps-server start 
+	
+	# Exit with success
+	return ${YEX_OK}    
 
 }
diff --git a/functions/config_storm_stop_gridhttps b/functions/config_storm_stop_gridhttps
--- a/functions/config_storm_stop_gridhttps
+++ b/functions/config_storm_stop_gridhttps
@@ -17,52 +17,53 @@
 # limitations under the License.
 ##############################################################################
 #
-# NAME :        config_storm_secure_tomcat
+# NAME :        config_storm_stop_gridhttps
 #
-# DESCRIPTION : This function configures tomcat
+# DESCRIPTION : This function stops gridhttps service
 #
 # AUTHORS :     michele.dibenedetto@cnaf.infn.it
 #
-# NOTES :       This function is taken from the config_secure_tomcat function written
-#               by Akos Frohner (Akos.Frohner@cern.ch) and Maria Alandes Pradillo (Maria.Alandes.Pradillo@cern.ch).
+# NOTES :     
 #
 # YAIM MODULE:  yaim-storm
 #                 
 ##############################################################################
 
-config_storm_stop_tomcat_check () {
+config_storm_stop_gridhttps_check () {
 
-  ret=0
-  detect_tomcat
-  if [ -z ${TOMCAT_VERSION} ]; then
-    yaimlog ERROR "Tomcat is probably not installed !"
-    yaimlog ERROR "${YERRORSTR}"
-    let "ret |= 1"
-  fi
-  return $ret
+  yaimlog INFO "No required variables to set."
 }
 
-config_storm_stop_tomcat_setenv () {
+config_storm_stop_gridhttps_setenv () {
 
   yaimlog INFO "No enviroment variables to set."
 }
 
-config_storm_stop_tomcat () {
+config_storm_stop_gridhttps () {
 
 
-####@ Check whether tomcat and java are installed
-
-yaimlog INFO "Check that java is installed"
-if [ ! -f /etc/java/java.conf ]; then
-  yestr ${YEX_NOSUCHFILE}
-  yaimlog ERROR "/etc/java/java.conf doesn't exist. Java is probably not installed !"
-  yaimlog ERROR "${YERRORSTR}"
-  exit ${YEX_NOSUCHFILE}
-fi
-
-yaimlog INFO "Stop tomcat in case it's running"
-service ${TOMCAT_VERSION} stop 
-
-return 0
+	####@ Check whether java are installed
+	
+	yaimlog INFO "Check that java is installed"
+	if [ ! -f /etc/java/java.conf ]; then
+	  yestr ${YEX_NOSUCHFILE}
+	  yaimlog ERROR "/etc/java/java.conf doesn't exist. Java is probably not installed !"
+	  yaimlog ERROR "${YERRORSTR}"
+	  exit ${YEX_NOSUCHFILE}
+	fi
+	
+	yaimlog INFO "Check that GridHTTPs is installed"
+	if [ ! -d /etc/storm/gridhttps-server ]; then
+	  yestr ${YEX_NOSUCHFILE}
+	  yaimlog ERROR "/etc/storm/gridhttps-server doesn't exist. StoRM GridHTTPs is probably not installed !"
+	  yaimlog ERROR "${YERRORSTR}"
+	  exit ${YEX_NOSUCHFILE}
+	fi
+	
+	yaimlog INFO "Stop GridHTTPs in case it's running"
+	service storm-gridhttps-server stop 
+	
+	# Exit with success
+	return ${YEX_OK}    
 
 }
